# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class GetEAadhaarDataInXMLFormatId404Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error: str=None, error_description: str=None):
        """GetEAadhaarDataInXMLFormatId404Response - a model defined in OpenAPI

        :param error: The error of this GetEAadhaarDataInXMLFormatId404Response.
        :param error_description: The error_description of this GetEAadhaarDataInXMLFormatId404Response.
        """
        self.openapi_types = {
            'error': str,
            'error_description': str
        }

        self.attribute_map = {
            'error': 'error',
            'error_description': 'error_description'
        }

        self._error = error
        self._error_description = error_description

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GetEAadhaarDataInXMLFormatId404Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Get_e_Aadhaar_Data_in_XML_Format_id_404_response of this GetEAadhaarDataInXMLFormatId404Response.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self):
        """Gets the error of this GetEAadhaarDataInXMLFormatId404Response.


        :return: The error of this GetEAadhaarDataInXMLFormatId404Response.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this GetEAadhaarDataInXMLFormatId404Response.


        :param error: The error of this GetEAadhaarDataInXMLFormatId404Response.
        :type error: str
        """
        allowed_values = ["aadhaar_not_linked", "aadhaar_not_available"]  # noqa: E501
        if error not in allowed_values:
            raise ValueError(
                "Invalid value for `error` ({0}), must be one of {1}"
                .format(error, allowed_values)
            )

        self._error = error

    @property
    def error_description(self):
        """Gets the error_description of this GetEAadhaarDataInXMLFormatId404Response.


        :return: The error_description of this GetEAadhaarDataInXMLFormatId404Response.
        :rtype: str
        """
        return self._error_description

    @error_description.setter
    def error_description(self, error_description):
        """Sets the error_description of this GetEAadhaarDataInXMLFormatId404Response.


        :param error_description: The error_description of this GetEAadhaarDataInXMLFormatId404Response.
        :type error_description: str
        """
        allowed_values = ["Aadhaar is not linked to the account", "Aadhaar data is not available for this user. Please perform Aadhaar eKYC again."]  # noqa: E501
        if error_description not in allowed_values:
            raise ValueError(
                "Invalid value for `error_description` ({0}), must be one of {1}"
                .format(error_description, allowed_values)
            )

        self._error_description = error_description
