# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class AuthError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error: str=None, error_description: str=None):
        """AuthError - a model defined in OpenAPI

        :param error: The error of this AuthError.
        :param error_description: The error_description of this AuthError.
        """
        self.openapi_types = {
            'error': str,
            'error_description': str
        }

        self.attribute_map = {
            'error': 'error',
            'error_description': 'error_description'
        }

        self._error = error
        self._error_description = error_description

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AuthError':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The auth-error of this AuthError.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self):
        """Gets the error of this AuthError.

        The name of the error.

        :return: The error of this AuthError.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this AuthError.

        The name of the error.

        :param error: The error of this AuthError.
        :type error: str
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")

        self._error = error

    @property
    def error_description(self):
        """Gets the error_description of this AuthError.

        The description of the error.

        :return: The error_description of this AuthError.
        :rtype: str
        """
        return self._error_description

    @error_description.setter
    def error_description(self, error_description):
        """Sets the error_description of this AuthError.

        The description of the error.

        :param error_description: The error_description of this AuthError.
        :type error_description: str
        """
        if error_description is None:
            raise ValueError("Invalid value for `error_description`, must not be `None`")

        self._error_description = error_description
