# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class ReturnASandboxAchTransferParameters(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, reason: str=None):
        """ReturnASandboxAchTransferParameters - a model defined in OpenAPI

        :param reason: The reason of this ReturnASandboxAchTransferParameters.
        """
        self.openapi_types = {
            'reason': str
        }

        self.attribute_map = {
            'reason': 'reason'
        }

        self._reason = reason

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ReturnASandboxAchTransferParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The return_a_sandbox_ach_transfer_parameters of this ReturnASandboxAchTransferParameters.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reason(self):
        """Gets the reason of this ReturnASandboxAchTransferParameters.

        The reason why the Federal Reserve or destination bank returned this transfer. Defaults to `no_account`.

        :return: The reason of this ReturnASandboxAchTransferParameters.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ReturnASandboxAchTransferParameters.

        The reason why the Federal Reserve or destination bank returned this transfer. Defaults to `no_account`.

        :param reason: The reason of this ReturnASandboxAchTransferParameters.
        :type reason: str
        """
        allowed_values = ["insufficient_fund", "no_account", "account_closed", "invalid_account_number_structure", "account_frozen_entry_returned_per_ofac_instruction", "credit_entry_refused_by_receiver", "unauthorized_debit_to_consumer_account_using_corporate_sec_code", "corporate_customer_advised_not_authorized", "payment_stopped", "non_transaction_account", "uncollected_funds", "routing_number_check_digit_error", "customer_advised_unauthorized_improper_ineligible_or_incomplete", "amount_field_error", "authorization_revoked_by_customer", "invalid_ach_routing_number", "file_record_edit_criteria", "enr_invalid_individual_name", "returned_per_odfi_request", "addenda_error", "limited_participation_dfi", "incorrectly_coded_outbound_international_payment", "other"]  # noqa: E501
        if reason not in allowed_values:
            raise ValueError(
                "Invalid value for `reason` ({0}), must be one of {1}"
                .format(reason, allowed_values)
            )

        self._reason = reason
